server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: vehicle-exit-pass
  
  # Disable metrics
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/pepsico_vehicle_pass
    username: ${DB_USERNAME:pepsico_user}
    password: ${DB_PASSWORD:pepsico123}
    driver-class-name: org.postgresql.Driver

# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
  # SQL Initialization
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql,classpath:update_schema.sql

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.pepsico: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Disable all metrics and actuator
management:
  metrics:
    enable:
      all: false
  endpoint:
    health:
      enabled: false
    metrics:
      enabled: false
    prometheus:
      enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: ""
      base-path: /management
  health:
    defaults:
      enabled: false
  info:
    env:
      enabled: false
  server:
    port: -1

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
logging:
  level:
    com.pepsico: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
